version: '3.8'

services:
  slenocard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - FRONTEND_PORT=80
      - BACKEND_PORT=5000
      - SERVER_HOST=0.0.0.0
      - DOMAIN=slenocard.com.br
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 